name: CI

env:
  CTEST_NO_TESTS_ACTION: error
  CTEST_PARALLEL_LEVEL: 0
  CMAKE_BUILD_PARALLEL_LEVEL: 4

on:
  push:
    paths:
    - "**.m"
    - "**.cpp"
    - "**.f90"
    - "**.cmake"
    - "**/CMakeLists.txt"
    - ".github/workflows/ci.yml"


jobs:

  linux:
    runs-on: ubuntu-latest

    steps:

    - name: Install Octave
      timeout-minutes: 10
      run: sudo apt install --no-install-recommends octave octave-dev

    - uses: actions/checkout@v4

    - name: CMake workflow
      run: cmake --workflow --preset default
